### ISSUE TITLE
There is a RCE vulnerability(needs to log in as admin).

### ISSUE THREAD

**Issue by xul18** [sunlight-cms/sunlight-cms#92]
A RCE vulnerability was discovered in SunLight CMS 8.
There is a CSRF attacks vulnerability.However, to exploit this vulnerability, the attacker needs to log in as admin.

1. Logged in http://*.*.*.*/sunlight-cms-master/admin/ .
![image](https://user-images.githubusercontent.com/22881765/223941199-3e135205-b25a-438c-970a-03be2e469aa0.png)

2. Open the page http://*.*.*.*/sunlight-cms-master/admin/script/php.php .
![image](https://user-images.githubusercontent.com/22881765/223941566-eb2dc286-c36c-4dc5-bbb8-071ddf174fc0.png)

3. Execute arbitrary code.
![image](https://user-images.githubusercontent.com/22881765/223941664-f3c191c8-06a7-4035-bda1-d539702ab3f5.png)

**Comment by jDanek** [comment]
The picture's not legible. If I read it correctly, there is no `system()` function in CMS.

**Comment by xul18** [comment]
The eval() function in page php.php can execute any PHP code.
If an attacker gains the admin's password through methods such as brute force, they can not only control the CMS, but also the server. 
I think this is not a secure design if CMS administrators can directly control the server. .

**Comment by ShiraNai7** [comment]
This is a feature, not a bug. There are more ways an admin could execute arbitrary PHP code:

- `[hcm]php,"some code"[/hcm]` in page content (requires "adminhcmphp" privilege)
- uploading a `.php` file using the file manager (requires "fileadminaccess" privilege)
- uploading a plugin via the plugin administration (requires "adminplugins" privilege)
- uploading a system patch in administration (only available to super admins)
- uploading and restoring a system backup (requires "adminbackup" privilege)

Being an admin is like having root access to the CMS. If someone "untrusted" needs to manage content, it is intended for them to be in a separate user group that doesn't have these privileges (the dangerous privileges are highlighted in red when editing a user group). I might add pre-configured group like that if that's a common use-case.

These functions exist because this CMS was designed to be used on a shared hosting. Shared hosts usually don't provide SSH access so many of these "admin" tasks can only be done through the browser.

> If an attacker gains the admin's password through methods such as brute force

Login attempts are limited so brute force should not be possible. Unless your database has leaked in which case you have bigger problems.

If you're really worried, you could remove the admin account's password so it's impossible to log into it.
